### ISSUE TITLE
Import job failed after updating RTF.API to version 6.0.0

### ISSUE THREAD

**Issue by joelmaciasvenegas** [relativitydev/relativity.testing.framework.api#262] opened 2022-01-10 18:18 UTC
### Describe the bug

RingSetup.TestSetup.OnSetup() fails to import docs.
The workspace created by RingSetup is created fine, but then fails to import docs.

### Steps to Reproduce

Run a test that uses RingSetup to create a testing workspace and import docs into that workspace.

### Relativity.Testing.Framework Version

7.1.0

### Relativity.Testing.Framework.API Version

6.0.1

### Relativity environment installation Type

RelativityOne

### Environment version

13.0.128.7

### Test Case

https://git.kcura.com/projects/DG/repos/searchtermsreport/browse/Source/Relativity.SearchTermsReport.FunctionalTests/RTFHelpers/RTFCDTestBase.cs#18

### Expected Behavior

Workspaces is created and default number of docs are imported.

### Actual Behavior

Docs fail to import.

### Additional Context

[stackTrace.txt](https://github.com/relativitydev/relativity.testing.framework.api/files/7841050/stackTrace.txt)
[Trace.log](https://github.com/relativitydev/relativity.testing.framework.api/files/7841066/Trace.log)

**Comment by paulletang** [comment] 2022-01-10 18:22
@joelmaciasvenegas 
Which R1 environment did you test against?
I want to reduce the number of variables as much as possible while trying to reproduce.

**Comment by joelmaciasvenegas** [comment] 2022-01-10 18:26
I tested against regression-a.
I also tested against a hopper using the template Tiger Lily EA Release Template [Do Not Delete] which is version 13.0.73.4
Got the same error in both environments.

**Comment by paulletang** [comment] 2022-01-10 22:56
This passes for me using the hopper image.
![image](https://user-images.githubusercontent.com/71905764/148851832-b202280b-b73f-46d6-91c6-7f163c0dbff5.png)


This fails for me on regression-a, but all of the workspaces are failing to upgrade there.
I think it's related.

**Comment by joelmaciasvenegas** [comment] 2022-01-10 23:21
@paulletang Nothing else comes to mind.
Did you add any toggles or install any additional RAPs to that hopper?

**Comment by paulletang** [comment] 2022-01-10 23:22
@joelmaciasvenegas no changes were made other than adding the default base artifacts (resource pool, client, matter).
Do you have time tomorrow to hop onto a call to try to reproduce this?

**Comment by joelmaciasvenegas** [comment] 2022-01-10 23:25
@paulletang Yes I do. Just ping me whenever you are free and I can hop on call.

**Comment by paulletang** [comment] 2022-01-11 17:15
We took a look at this using a couple of different codebases, and on both of our computers.
It looks like there is something in the codebase that Joel is using that is causing this.

@joelmaciasvenegas I'm going to close this out, but feel free to reopen if you discover anything that points back to the Relativity.Testing.Framework repositories, or some configuration that we should be handling better.

**Closed by paulletang** 2022-01-11 17:15 UTC
Labels: bug
